language: node_js
cache:
  directories:
    - node modules
    - ~/.npm
node_js:
  - 'node'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - gsusqdavid@gmail.com
      - 15-10345@usb.ve
    on_success: always
deploy:
  provider: pages
  edge: true
  skip-cleanup : true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master
